### ISSUE TITLE
Symbol not found: _kIOMasterPortDefault

### ISSUE THREAD

**Issue by mmikhan** [ayoubserti/node-iohook#13]
Unfortunately, the addon doesn't work and shows the following error:
```shell
Error: dlopen(/Users/mazik/Desktop/hello/node_modules/node-iohook/build/Release/node-iohook.node, 1): Symbol not found: _kIOMasterPortDefault
  Referenced from: /Users/mazik/Desktop/hello/node_modules/node-iohook/build/Release/node-iohook.node
  Expected in: flat namespace
 in /Users/mazik/Desktop/hello/node_modules/node-iohook/build/Release/node-iohook.node
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/mazik/Desktop/hello/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/mazik/Desktop/hello/node_modules/node-iohook/index.js:3:42)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

Any idea why `Symbol not found: _kIOMasterPortDefault` is not found from the `node-iohook.node`?

**Comment by ayoubserti** [comment]
As I could see it's a problem within MAC. It came from IOKit framework which is used by `libuiohook`. 

What's your Mac version ?  and what's your nodejs one?
