### ISSUE TITLE
electron 1.6.1 -  Error: The specified module could not be found.

### ISSUE THREAD

**Issue by aknuth** [ayoubserti/node-iohook#4]
Hi Ayoub,
using the new electron 1.6.1 and node.js 7.4.0 version I get into trouble after a new build (npm install):
```
The following error occurs:
C:\git\node-iohook>node main.js
C:\git\node-iohook\node_modules\bindings\bindings.js:83
        throw e
        ^
Error: The specified module could not be found.
\\?\C:\git\node-iohook\build\Release\node-iohook.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (C:\git\node-iohook\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\git\node-iohook\index.js:3:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```
I also replaced the runtimeVersion of cmake-js in package.json to 1.6.1.
```
...  
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.6.1"
    
  }
...
```

Can you reproduce this problem and do you have an explanation/solution ?
cheers,
Andreas

**Comment by aknuth** [comment]
I got it up now ! seemed to be a node.js version problem between the installed node.js and the electron bundled node.js

**Comment by joravkumar** [comment]
Hii @aknuth 
I am facing the same issue. Can u please provide me the solution??
Attached Screenshot

![iohook nod problem](https://user-images.githubusercontent.com/42232691/86439057-6a1dd100-bd25-11ea-8fbe-3f93db8f35a3.jpg)
